@startuml
folder logger  #DDDDDD {

    component core #00000 {
        package logger.core #FFFFCC{
               
        }
        package logger.json #FFFFCC{

        }
    }

    component fxui #00000 {
        package logger.fxui #FFFFCC{
        }
    }

    component resources #00000 {
        component fxml {
                
        }
    }
    component rest #00000 {
        package logger.rest #FFFFCC {

        }
    }

    component springboot {

    }

    component jackson {

    }

}

logger.fxui ..> fxml

logger.fxui ..> logger.json
logger.fxui ..> logger.core

rest .> springboot

logger.json ..> jackson

logger.rest ..> logger.json

logger.rest ..> logger.core

logger.fxui .> logger.rest

@enduml