@startuml
folder logger  #DDDDDD {

    component core #00000 {
        package logger.core #FFFFCC{
               
            }
            package logger.json #FFFFCC{

            }
        }

    component fxui #00000 {
        package logger.fxui #FFFFCC{
            
        }
    }

    component javafx #00000 {
        component fxml {
                
        }
    }

    component restserver #00000 {
        package logger.restserver #FFFFCC {
                
        }
        package logger.restapi #FFFFCC {
                
        }
    }

    component springboot {

    }

    component jackson {

    }

}

fxui ..> javafx
fxui ..> fxml

logger.fxui ..> logger.json
logger.fxui ..> logger.core

restserver ..> springboot

logger.json ..> jackson

logger.restapi ..> logger.core
logger.restapi ..> logger.json


logger.restserver ..> logger.restapi
logger.restserver ..> logger.core

@enduml