@startuml
folder logger  #DDDDDD {

    component core #00000 {
        package logger.core #FFFFCC{
               
            }
            package logger.json #FFFFCC{

            }
        }

    component fxui #00000 {
        package logger.ui #FFFFCC{
            
        }
    }

    component javafx #00000 {
        component App.fxml {
                
        }
    }

}

fxui --> javafx
fxui --> App.fxml

logger.ui --> logger.json
logger.ui --> logger.core



@enduml